jobs_project/config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  root "main#index"

  get 'main/about'

  get "main/two_columns"

  get "main/jobs"

  resources :companies

  resources :jobs

  resources :reviews

  resources :contact

end

jobs_project/app/models/company.rb
class Company < ActiveRecord::Base
end

jobs_project/app/models/job.rb
class Job < ActiveRecord::Base
end

jobs_project/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json

  def contact
    @contact = Contact.new
  end
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  def show_first_10
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:industry, :function, :number_of_jobs, :company_name, :founded_date)
    end
end

jobs_project/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:date_posted, :date_applied, :interview, :interviewed_by, :notes)
    end
end

jobs_project/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def about
  end


 def ten_columns
 end
end

jobs_project/app/helpers/companies_helper.rb
module CompaniesHelper
end

jobs_project/app/helpers/jobs_helper.rb
module JobsHelper
end

jobs_project/app/helpers/main_helper.rb
module MainHelper
end

jobs_project/app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_posted %><br>
    <%= f.datetime_select :date_posted %>
  </div>
  <div class="field">
    <%= f.label :date_applied %><br>
    <%= f.datetime_select :date_applied %>
  </div>
  <div class="field">
    <%= f.label :interview %><br>
    <%= f.check_box :interview %>
  </div>
   <div class="field">
    <%= f.label :interviewed_by %><br>
    <%= f.text_field :interviewed_by %>
  </div>
    <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jobs_project/app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

jobs_project/app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <thead>
    <tr>
      <th>Date posted</th>
      <th>Date applied</th>
      <th>Interview</th>
       <th>Interviewed By</th>
       <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.date_posted %></td>
        <td><%= job.date_applied %></td>
        <td><%= job.interview %></td>
        <td><%= job.interviewed_by %></td>
        <td><%= job.notes %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

jobs_project/app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

jobs_project/app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date posted:</strong>
  <%= @job.date_posted %>
</p>

<p>
  <strong>Date applied:</strong>
  <%= @job.date_applied %>
</p>

<p>
  <strong>Interview:</strong>
  <%= @job.interview %>
</p>

<p>
  <strong>Interviewed By:</strong>
  <%= @job.interviewed_by %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @job.notes %>
</p>
<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>