lifeletters/config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/about'

  get 'welcome/index'

  get 'loved_ones/add_loved_one'

  get 'welcome/loved_ones' => 'loved_ones#number_loved_ones'

  get 'welcome/add_liaison' => 'loved_ones#add_liaison'

  post 'loved_ones/number_loved_ones'

  root "welcome#index"

  resources :loved_ones

  resources :users

end

lifeletters/app/models/loved_one.rb
class LovedOne < ActiveRecord::Base


	validates :first_name, presence: true

	validates :last_name, presence: true

	belongs_to :user

end

lifeletters/app/models/user.rb
class User < ActiveRecord::Base

	has_many :loved_ones

end

lifeletters/app/controllers/loved_ones_controller.rb
class LovedOnesController < ApplicationController
  before_action :set_loved_one, only: [:show, :edit, :update, :destroy]

  # GET /loved_ones
  # GET /loved_ones.json
  def index
    @loved_ones = LovedOne.all
  end

  # GET /loved_ones/1
  # GET /loved_ones/1.json
  def show
  end

  # GET /loved_ones/new
  def new
    @loved_one = LovedOne.new
  end

  # GET /loved_ones/1/edit
  def edit
  end

  # POST /loved_ones
  # POST /loved_ones.json

  def add_loved_one
    first_name = params[:first_name]
    last_name = params[:last_name]

    new_loved_one = LovedOne.new

    new_loved_one.first_name = first_name
    new_loved_one.last_name = last_name

  end

  def add_liaison

  end

  def create
    @loved_one = LovedOne.new(loved_one_params)

    respond_to do |format|
      if @loved_one.save
        format.html { redirect_to @loved_one, notice: 'Loved one was successfully created.' }
        format.json { render :show, status: :created, location: @loved_one }
      else
        format.html { render :new }
        format.json { render json: @loved_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loved_ones/1
  # PATCH/PUT /loved_ones/1.json
  def update
    respond_to do |format|
      if @loved_one.update(loved_one_params)
        format.html { redirect_to @loved_one, notice: 'Loved one was successfully updated.' }
        format.json { render :show, status: :ok, location: @loved_one }
      else
        format.html { render :edit }
        format.json { render json: @loved_one.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loved_ones/1
  # DELETE /loved_ones/1.json
  def destroy
    @loved_one.destroy
    respond_to do |format|
      format.html { redirect_to loved_ones_url, notice: 'Loved one was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loved_one
      @loved_one = LovedOne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loved_one_params
      params.require(:loved_one).permit(:first_name, :last_name, :user_id)
    end
end

lifeletters/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

lifeletters/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end

  def index
  end
end

lifeletters/app/helpers/loved_ones_helper.rb
module LovedOnesHelper
end

lifeletters/app/helpers/users_helper.rb
module UsersHelper
end

lifeletters/app/helpers/welcome_helper.rb
module WelcomeHelper
end

lifeletters/app/views/loved_ones/_form.html.erb
<%= form_for(@loved_one) do |f| %>
  <% if @loved_one.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loved_one.errors.count, "error") %> prohibited this loved_one from being saved:</h2>

      <ul>
      <% @loved_one.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lifeletters/app/views/loved_ones/add_liaison.html.erb
<% link_to 'Add Loved One', loved_ones_number_loved_ones_path %>

lifeletters/app/views/loved_ones/add_loved_one.html.erb
<h1>How many loved ones would you like?</h1>


<% @loved_ones.each do |loved_one| %>
	<%= f.label :number_loved_ones %><br>
    <%= f.number_field :number_loved_ones %>



<% end%>
 

lifeletters/app/views/loved_ones/edit.html.erb
<h1>Editing loved_one</h1>

<%= render 'form' %>

<%= link_to 'Show', @loved_one %> |
<%= link_to 'Back', loved_ones_path %>

lifeletters/app/views/loved_ones/index.html.erb
<h1>Listing loved_ones</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loved_ones.each do |loved_one| %>
      <tr>
        <td><%= loved_one.first_name %></td>
        <td><%= loved_one.last_name %></td>
        <td><%= loved_one.user_id %></td>
        <td><%= link_to 'Show', loved_one %></td>
        <td><%= link_to 'Edit', edit_loved_one_path(loved_one) %></td>
        <td><%= link_to 'Destroy', loved_one, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loved one', new_loved_one_path %>

lifeletters/app/views/loved_ones/new.html.erb
<h1>New loved_one</h1>

<%= render 'form' %>

<%= link_to 'Back', loved_ones_path %>

lifeletters/app/views/loved_ones/number_loved_ones.html.erb
<%=form_tag("/loved_ones/number_loved_ones", method: "post") do %>
	<%= label_tag(:number_loved_ones, "Number of Loved Ones")%>
	<%= text_field_tag(:number_loved_ones)%>
	<%= submit_tag("Go")%>
<%end%>

lifeletters/app/views/loved_ones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @loved_one.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @loved_one.last_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @loved_one.user_id %>
</p>

<%= link_to 'Edit', edit_loved_one_path(@loved_one) %> |
<%= link_to 'Back', loved_ones_path %>